url: https://iotdayit.github.io
baseurl: ""

# Site settings
title: IoT Day Italy
email: info@iotdayit.org
description: "IoT Day Italy is the Italian conference focused on Internet of Thins, Industry 4.0 and Digital Transformation"

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/iotdayit
  - title: facebook
    url: https://www.facebook.com/iotdayit/

location: Università degli Studi di Napoli Federico II - Scuola Politecnica e delle Scienze di Base - Complesso Napoli Est

# Status of the conference organization (speakers and session available, c4p started, ...)
conference:
  speakers: false
  sessions: false
  registration: false

# Build settings
markdown: kramdown
permalink: pretty